SippyShop/SippyShop/Areas/Admin/Controllers/tblProductsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SippyShop.Models;

namespace SippyShop.Areas.Admin.Controllers
{
    public class tblProductsController : Controller
    {
        private SippyShopEntities db = new SippyShopEntities();

        // GET: Admin/tblProducts
        public ActionResult Index(string searchValue)
        {
            Session.Add("PAGE", "Product");
            var tblProducts = db.tblProducts.Include(t => t.tblCategory);
            if (searchValue != null)
            {
                tblProducts = from t in db.tblProducts where t.name.Contains(searchValue) select t;
            }
          
            return View(tblProducts.ToList());
        }

        // GET: Admin/tblProducts/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tblProduct tblProduct = db.tblProducts.Find(id);
            if (tblProduct == null)
            {
                return HttpNotFound();
            }
            return View(tblProduct);
        }

        // GET: Admin/tblProducts/Create
        public ActionResult Create()
        {
            ViewBag.categoryId = new SelectList(db.tblCategories, "categoryId", "name");
            return View();
        }

        // POST: Admin/tblProducts/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [ValidateInput (false)]
        public ActionResult Create([Bind(Include = "productId,name,quantity,price,sale,img,detail,categoryId")] tblProduct tblProduct,HttpPostedFileBase img)
        {
            var path = "";
            var fileName = "";
            if (ModelState.IsValid)
            {
                tblProduct pro = db.tblProducts.Find(tblProduct.productId);
                if (pro != null)
                {
                    Session.Add("DUPLICATEPRO", "Duplicate Product ID");
                    ViewBag.categoryId = new SelectList(db.tblCategories, "categoryId", "name", tblProduct.categoryId);
                    return View(tblProduct);

                }
               
                if (img != null)
                {
                    fileName = img.FileName;
                    path = Path.Combine(Server.MapPath("~/Content/image"), fileName);
                    img.SaveAs(path);
                    tblProduct.img = "/Content/image/" + fileName;
                }
                else
                {
                    tblProduct.img = null;
                }
              
                db.tblProducts.Add(tblProduct);
                db.SaveChanges();
                Session.Remove("DUPLICATEPRO");
                return RedirectToAction("Index");
            }
          
            ViewBag.categoryId = new SelectList(db.tblCategories, "categoryId", "name", tblProduct.categoryId);
            return View(tblProduct);
        }

        // GET: Admin/tblProducts/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tblProduct tblProduct = db.tblProducts.Find(id);
            if (tblProduct == null)
            {
                return HttpNotFound();
            }
            ViewBag.categoryId = new SelectList(db.tblCategories, "categoryId", "name", tblProduct.categoryId);
            return View(tblProduct);
        }

        // POST: Admin/tblProducts/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "productId,name,quantity,price,sale,detail,categoryId")] tblProduct tblProduct,HttpPostedFileBase img)
        {
            if (ModelState.IsValid)
            {
                var fileName = "";
                var path = "";
                if (img != null)
                {
                    fileName = img.FileName;
                    path = Path.Combine(Server.MapPath("~/Content/image"), fileName);
                    img.SaveAs(path);
                    tblProduct.img = "/Content/image/" + fileName;
                }
               
                db.Entry(tblProduct).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.categoryId = new SelectList(db.tblCategories, "categoryId", "name", tblProduct.categoryId);
            return View(tblProduct);
        }

        // GET: Admin/tblProducts/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tblProduct tblProduct = db.tblProducts.Find(id);
            if (tblProduct == null)
            {
                return HttpNotFound();
            }
            return View(tblProduct);
        }

        // POST: Admin/tblProducts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            tblProduct tblProduct = db.tblProducts.Find(id);
            db.tblProducts.Remove(tblProduct);
           
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

SippyShop/SippyShop/Areas/Admin/Views/tblProducts/Create.cshtml
@model SippyShop.Models.tblProduct

@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/Admin/Views/Shared/AdminView.cshtml";
}

<h2 >Create</h2>

@using (Html.BeginForm("Create", "tblProducts", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4>tblProduct</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.productId, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.productId, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.productId, "", new { @class = "text-danger" })
            @if (Session["DUPLICATEPRO"] != null)
            {
                <h3 class="danger">@Session["DUPLICATEPRO"]</h3>
            }
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.name, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.name, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.name, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.quantity, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.quantity, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.quantity, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.price, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.price, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.price, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.sale, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.sale, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.sale, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.img, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">

            <input type="file" name="img" />
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.detail, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.detail, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.detail, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.categoryId, "categoryId", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("categoryId", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.categoryId, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

SippyShop/SippyShop/Areas/Admin/Views/tblProducts/Delete.cshtml
@model SippyShop.Models.tblProduct

@{
    ViewBag.Title = "Delete";
    Layout = "~/Areas/Admin/Views/Shared/AdminView.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>tblProduct</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.quantity)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.quantity)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.price)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.price)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.sale)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.sale)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.img)
        </dt>

        <dd>
          <img src="@Model.img"/>
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.tblCategory.name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.tblCategory.name)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

SippyShop/SippyShop/Areas/Admin/Views/tblProducts/Details.cshtml
@model SippyShop.Models.tblProduct

@{
    ViewBag.Title = "Details";
    Layout = "~/Areas/Admin/Views/Shared/AdminView.cshtml";
}

<h2>Details</h2>

<div>
    <h4>tblProduct</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.quantity)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.quantity)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.price)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.price)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.sale)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.sale)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.img)
        </dt>

        <dd>
            <img src="@Model.img" />
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.detail)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.detail)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.tblCategory.name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.tblCategory.name)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.productId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

SippyShop/SippyShop/Areas/Admin/Views/tblProducts/Edit.cshtml
@model SippyShop.Models.tblProduct

@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/AdminView.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm("Edit","tblProducts",FormMethod.Post,new { enctype="multipart/form-data"}))
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>tblProduct</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.productId)

    <div class="form-group">
        @Html.LabelFor(model => model.name, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.name, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.name, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.quantity, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.quantity, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.quantity, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.price, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.price, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.price, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.sale, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.sale, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.sale, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.detail, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.detail, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.detail, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.img, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <img src="@Model.img" />
            <input type="file" name="img" />
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.categoryId, "categoryId", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("categoryId", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.categoryId, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Save" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

SippyShop/SippyShop/Areas/Admin/Views/tblProducts/Index.cshtml
@model IEnumerable<SippyShop.Models.tblProduct>

@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/AdminView.cshtml";
}

<h2>Product</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.quantity)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.price)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.sale)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.img)
        </th>
        <th>
          Category
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.quantity)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.price)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.sale)
        </td>
        <td>
          <img src="@item.img" style="width:50px"/>
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.tblCategory.name)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.productId }) |
            @Html.ActionLink("Details", "Details", new { id=item.productId }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.productId })
        </td>
    </tr>
}

</table>