SippyShop/SippyShop/Areas/Admin/Controllers/tblUsersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SippyShop.Models;

namespace SippyShop.Areas.Admin.Controllers
{
    public class tblUsersController : Controller
    {
        private SippyShopEntities db = new SippyShopEntities();

        // GET: Admin/tblUsers
        public ActionResult Index(string searchValue)
        {
            Session.Add("PAGE", "User");
            var tblUser = from t in db.tblUsers select t;
            if (searchValue != null)
            {
                tblUser = from t in db.tblUsers where t.name.Contains(searchValue) select t;
            }
            return View(tblUser.ToList());
        }

        // GET: Admin/tblUsers/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tblUser tblUser = db.tblUsers.Find(id+".com");
            if (tblUser == null)
            {
                return HttpNotFound();
            }
            return View(tblUser);
        }

        // GET: Admin/tblUsers/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Admin/tblUsers/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "name,password,role,phoneNum,img,email,address")] tblUser tblUser,HttpPostedFileBase img)
        {
            if (ModelState.IsValid)
            {
                tblUser pro = db.tblUsers.Find(tblUser.email);
                if (pro != null)
                {
                    Session.Add("DUPLICATEUSE", "Duplicate EMAIL");
                    return View(tblUser);
                }
               
                var fileName = "";
                var path = "";
                if (img != null)
                {
                    fileName = img.FileName;
                    path = Path.Combine(Server.MapPath("~/Content/image"), fileName);
                    img.SaveAs(path);
                    tblUser.img = "/Content/image/" + fileName;
                }
                else
                {
                    tblUser.img = null;
                }
                db.tblUsers.Add(tblUser);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
       
            return View(tblUser);
        }

        // GET: Admin/tblUsers/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tblUser tblUser = db.tblUsers.Find(id+".com");
            if (tblUser == null)
            {
                return HttpNotFound();
            }
            return View(tblUser);
        }

        // POST: Admin/tblUsers/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "name,password,role,phoneNum,img,email,address")] tblUser tblUser,HttpPostedFileBase img)
        {
            var fileName = "";
            var path = "";
            if (ModelState.IsValid)
            {
                if (img != null)
                {
                    fileName = img.FileName;
                    path = Path.Combine(Server.MapPath("~/Content/image"),fileName);
                    img.SaveAs(path);
                    tblUser.img = "/Content/image/" + fileName;
                }
                else
                {
                    tblUser.img = null;
                }

                db.Entry(tblUser).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(tblUser);
        }

        // GET: Admin/tblUsers/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tblUser tblUser = db.tblUsers.Find(id+".com");
            if (tblUser == null)
            {
                return HttpNotFound();
            }
            return View(tblUser);
        }

        // POST: Admin/tblUsers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            tblUser tblUser = db.tblUsers.Find(id);
            db.tblUsers.Remove(tblUser);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

SippyShop/SippyShop/Areas/Admin/Views/tblUsers/Create.cshtml
@model SippyShop.Models.tblUser

@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/Admin/Views/Shared/AdminView.cshtml";
}

<h2>Create</h2>

@using (Html.BeginForm("Create","tblUsers",FormMethod.Post,new { enctype="multipart/form-data"}))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>tblUser</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.name, "", new { @class = "text-danger" })
               
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.password, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.password, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.password, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.role, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.role, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.role, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.phoneNum, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.phoneNum, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.phoneNum, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.img, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
             <input type="file" name="img" accept=".png,.gif,.peg"/>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.email, "", new { @class = "text-danger" })
                @if (Session["DUPLICATEUSE"] != null)
                {
                    <h3 style="color:red">@Session["DUPLICATEUSE"]</h3>
                }
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.address, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.address, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.address, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

SippyShop/SippyShop/Areas/Admin/Views/tblUsers/Delete.cshtml
@model SippyShop.Models.tblUser

@{
    ViewBag.Title = "Delete";
    Layout = "~/Areas/Admin/Views/Shared/AdminView.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>tblUser</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.password)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.password)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.role)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.role)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.phoneNum)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.phoneNum)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.img)
        </dt>

        <dd>
          <img src="@Model.img"/>
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.address)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.address)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

SippyShop/SippyShop/Areas/Admin/Views/tblUsers/Details.cshtml
@model SippyShop.Models.tblUser

@{
    ViewBag.Title = "Details";
    Layout = "~/Areas/Admin/Views/Shared/AdminView.cshtml";
}

<h2>Details</h2>

<div>
    <h4>tblUser</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.password)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.password)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.role)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.role)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.phoneNum)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.phoneNum)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.img)
        </dt>

        <dd>
          
            <img src="@Model.img"/>
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.address)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.address)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.email }) |
    @Html.ActionLink("Back to List", "Index")
</p>

SippyShop/SippyShop/Areas/Admin/Views/tblUsers/Edit.cshtml
@model SippyShop.Models.tblUser

@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/AdminView.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>tblUser</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.password, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.password, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.password, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.role, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.role, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.role, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.phoneNum, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.phoneNum, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.phoneNum, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.img, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
              <img src="@Model.img"/>
                <input type="file" name="img"/>
            </div>
        </div>

        @Html.HiddenFor(model => model.email)

        <div class="form-group">
            @Html.LabelFor(model => model.address, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.address, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.address, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

SippyShop/SippyShop/Areas/Admin/Views/tblUsers/Index.cshtml
@model IEnumerable<SippyShop.Models.tblUser>

@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/AdminView.cshtml";
}

<h2>Account</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.email)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.password)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.role)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.phoneNum)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.img)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.address)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.email)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.password)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.role)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.phoneNum)
        </td>
        <td>
         <img src="@item.img"/>
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.address)
        </td>
        <td>
         <a href=" @Url.Action("Edit","tblUsers",new { id=item.email.Substring(0,item.email.IndexOf("."))})">Edit</a>|
            @Html.ActionLink("Details", "Details", new { id=item.email.Substring(0, item.email.IndexOf(".")) }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.email.Substring(0, item.email.IndexOf(".")) })
        </td>
    </tr>
}

</table>